2025-06-24 22:49:49,237 - INFO - UI - Replicação de dados iniciada
2025-06-24 22:49:49,622 - INFO - REPLICATION - Recarregando tarefa
2025-06-24 22:49:49,622 - INFO - REPLICATION - Recriando tabelas de metadata
2025-06-24 22:49:49,831 - INFO - TASK - fl_cdc_upsert_employees válido
2025-06-24 22:49:49,831 - CRITICAL - trempy.Tasks.Exceptions.Exception.AddFilterError: TASK - Tabela não encontrada | employees.employee
2025-06-24 22:49:56,044 - ERROR - builtins.str: UI - Erro ao parar replicação: process PID not found (pid=12452)
